-- ============================================
-- CONFIGURACIÓN DE TABLA DE BIBLIOTECAS (Libraries)
-- Ejecuta este SQL en tu dashboard de Supabase
-- ============================================

-- 1. Crear la tabla de bibliotecas (libraries)
CREATE TABLE IF NOT EXISTS bibliotecas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  es_publica BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Crear índice para búsquedas por usuario
CREATE INDEX IF NOT EXISTS idx_bibliotecas_user_id ON bibliotecas(user_id);

-- 3. Habilitar RLS en la tabla bibliotecas
ALTER TABLE bibliotecas ENABLE ROW LEVEL SECURITY;

-- 4. Políticas para bibliotecas
-- Permitir a los usuarios ver sus propias bibliotecas
CREATE POLICY "Users can view own libraries" ON bibliotecas
  FOR SELECT USING (auth.uid() = user_id);

-- Permitir a los usuarios insertar sus propias bibliotecas
CREATE POLICY "Users can create own libraries" ON bibliotecas
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Permitir a los usuarios actualizar sus propias bibliotecas
CREATE POLICY "Users can update own libraries" ON bibliotecas
  FOR UPDATE USING (auth.uid() = user_id);

-- Permitir a los usuarios eliminar sus propias bibliotecas
CREATE POLICY "Users can delete own libraries" ON bibliotecas
  FOR DELETE USING (auth.uid() = user_id);

-- 5. Añadir columna biblioteca_id a la tabla books/libros si no existe
ALTER TABLE IF EXISTS books ADD COLUMN IF NOT EXISTS biblioteca_id BIGINT;
ALTER TABLE IF EXISTS libros ADD COLUMN IF NOT EXISTS biblioteca_id BIGINT;

-- 6. Crear referencia entre libros y bibliotecas (opcional)
ALTER TABLE IF EXISTS books 
  ADD CONSTRAINT fk_books_biblioteca 
  FOREIGN KEY (biblioteca_id) REFERENCES bibliotecas(id) ON DELETE CASCADE;

ALTER TABLE IF EXISTS libros 
  ADD CONSTRAINT fk_libros_biblioteca 
  FOREIGN KEY (biblioteca_id) REFERENCES bibliotecas(id) ON DELETE CASCADE;

-- 7. Actualizar la política de books para incluir biblioteca_id
CREATE OR REPLACE POLICY "Users can view own books" ON books
  FOR SELECT USING (
    auth.uid() = user_id 
    OR EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

CREATE OR REPLACE POLICY "Users can insert own books" ON books
  FOR INSERT WITH CHECK (
    auth.uid() = user_id 
    OR EXISTS (
      SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- 8. Crear una biblioteca por defecto para usuarios existentes (opcional)
-- Descomentar y ejecutar si quieres que todos los usuarios tengan una biblioteca por defecto
-- INSERT INTO bibliotecas (nombre, user_id)
-- SELECT 'Mi Biblioteca', id FROM users 
-- ON CONFLICT (user_id) DO NOTHING;
