-- 📚 SCRIPT DE CONFIGURACIÓN DE BASE DE DATOS EN SUPABASE
-- Ejecuta este script en el editor SQL de tu panel de Supabase (SQL Editor > New Query > Run)

-- 1. Crear la tabla de libros
create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  titulo text not null,
  autor text,
  isbn text,
  editorial text,
  anio text,
  descripcion text,
  portada_url text,
  precio_compra numeric(10, 2),
  precio_venta numeric(10, 2),
  fecha_compra date,
  real_photos text[] default '{}', -- Array de imágenes en Base64
  fecha_registro timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar la seguridad a nivel de fila (Row Level Security - RLS)
-- Esto garantiza que nadie pueda ver tus libros aunque tengan tu API Key pública de Supabase
alter table public.books enable row level security;

-- 3. Crear políticas de seguridad para que solo el propietario de los libros pueda verlos/gestionarlos

-- Política para permitir lectura (SELECT) únicamente de tus propios libros
create policy "Los usuarios solo pueden ver sus propios libros"
  on public.books for select
  using (auth.uid() = user_id);

-- Política para permitir inserción (INSERT) de libros únicamente bajo tu propio id de usuario
create policy "Los usuarios solo pueden añadir sus propios libros"
  on public.books for insert
  with check (auth.uid() = user_id);

-- Política para permitir actualización (UPDATE) únicamente de tus propios libros
create policy "Los usuarios solo pueden actualizar sus propios libros"
  on public.books for update
  using (auth.uid() = user_id);

-- Política para permitir eliminación (DELETE) únicamente de tus propios libros
create policy "Los usuarios solo pueden eliminar sus propios libros"
  on public.books for delete
  using (auth.uid() = user_id);

-- 4. Crear índice para optimizar búsquedas por usuario
create index if not exists books_user_id_idx on public.books(user_id);
