-- ============================================
-- SQL MINIMO PARA CREAR SOLO LA TABLA BIBLIOTECAS
-- Ejecuta este script si el otro da error
-- ============================================

-- 1. Crear SOLO la tabla de bibliotecas
CREATE TABLE IF NOT EXISTS bibliotecas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  es_publica BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Crear índice para búsquedas por usuario
CREATE INDEX IF NOT EXISTS idx_bibliotecas_user_id ON bibliotecas(user_id);

-- 3. Habilitar RLS en bibliotecas
ALTER TABLE bibliotecas ENABLE ROW LEVEL SECURITY;

-- 4. Políticas básicas para bibliotecas
CREATE POLICY "Users can view own libraries" ON bibliotecas
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own libraries" ON bibliotecas
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own libraries" ON bibliotecas
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own libraries" ON bibliotecas
  FOR DELETE USING (auth.uid() = user_id);

-- 5. Añadir columna biblioteca_id a la tabla books (SOLO si no existe)
ALTER TABLE IF EXISTS books ADD COLUMN IF NOT EXISTS biblioteca_id BIGINT;
ALTER TABLE IF EXISTS libros ADD COLUMN IF NOT EXISTS biblioteca_id BIGINT;
